name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ["8.1", "8.2", "8.3"]
        laravel: [^10.0, ^11.0]
        include:
          - laravel: ^10.0
            testbench: ^8.0
          - laravel: ^11.0
            testbench: ^9.0
        exclude:
          - laravel: ^11.0
            php: "8.1"

    name: Laravel ${{ matrix.laravel }} PHP${{ matrix.php }} on ${{ matrix.os }}

    container:
      image: lorisleiva/laravel-docker:${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer files
        run: composer validate

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: /composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer require --prefer-dist --no-progress --no-suggest --no-interaction "illuminate/support:${{ matrix.laravel }}"
          composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run tests
        run: phpunit
